version: 4.0.0
name: momiji
description: m68k emulator infrastructure
repository: https://github.com/andry-dev/momiji
exclude:
    - ".gitignore"
    - "vendor"
baseurl: /momiji/
plugins:
    - jekyll-liquify
